### ISSUE TITLE
Module 4F: Slide Label/low-res Imaging [1st Draft Completion List]

### ISSUE THREAD

**Issue by tmcelrath** [EntCollNet/BugFlow#72]
[Module 4F: Slide Label/low-res Imaging](https://github.com/EntCollNet/BugFlow/blob/master/modules/module_4/module_4F.md)
- [x] Title created
- [x] Purpose created
- [x] Keywords created
- [x] Point Person assigned
- [x] Task List filled in
- [x] Essential training added
- [x] Metrics costing reporting filled in
- [x] Outreach opportunities filled in
- [x] Exemplar workflows added
- [x] References to other Modules added/linked
- [x] Discussion section added at bottom
- [x] Links to standards/Best practices

**Comment by tmcelrath** [comment]
https://www.idigbio.org/wiki/images/3/30/Scanning_Microscope_Slides_Oboyski.pdf

**Comment by tmcelrath** [comment]
Contact: langane@si.edu, langane@si.edu, langane@si.edu

**Comment by tmcelrath** [comment]
@EMTuckerLabUMMZ using Inselect to crop and save: https://drive.google.com/drive/u/0/folders/1ptvL7xFldeErq2AvU62xIFbeB3enpey-

**Comment by dryopoiddarling** [comment]
Move text for T1 "Explanation and Comments" to "Module Purpose"

**Comment by debpaul** [comment]
- [ ] Add this as a general reference https://cordis.europa.eu/docs/report/docs-results-312-312253-final1-synthesys3-final-publishable-summary.pdf

**Comment by debpaul** [comment]
- [ ] Add this resource https://bdj.pensoft.net/article/32342/
Allan E, Livermore L, Price B, Shchedrina O, Smith V (2019) **A Novel Automated Mass Digitisation Workflow for Natural History Microscope Slides**. Biodiversity Data Journal 7: e32342. https://doi.org/10.3897/BDJ.7.e32342

**Comment by dryopoiddarling** [comment]
Reorder and rewrite t4-t7 to take into consideration data that is communicated in location in box. Consider whether they need to be reorganized or not, based on the workflows of the institution.

**Comment by dryopoiddarling** [comment]
Reverse T11 and T12

**Comment by debpaul** [comment]
For T9. Suggest referring to better practices involving image file names. Best practice would not put metadata like taxon name in the file name (since this could change and then makes image tracking and handling more challenging). One needs to depend on one's database to know what the images depict.

**Task Name Now:** Save/name image file in a standard, institutionally determined format, if necessary. Some databases do not need this step.

**Task Name Suggestion:** Save/name image file in a standard, institutionally or project-specific determined format, if necessary. Best practices would use only alphanumeric identifiers and avoid putting any specific metadata like genus or species names in the file names because these data could change. 

**Explanations and Comments Now:** A file-naming scheme that mirrors the collecting event identifier is sometimes used. Examples might include: "country code"+"state code"+"verbatim directions"+"collector name"+"date"+"serial identifier", or a subset of these. This can also be done using batch renaming using programs like Adobe Bridge, IrfanView (free), or Inselect (free). Inselect can also parse out multiple slides in one image, read QR codes, and rename files based on the embedded information. DO NOT USE SPACES IN FILENAMES

**Explanations and Comments Suggestion:** A best practice file-naming scheme would use only the number that comes form the camera, possibly concatenated using an underscore "_" with other numbers such as location in the collection or other identifier that would likely not change such as the relevant collecting event identifier. Examples might include: "camera number" _ "location in collection" or what is needed to track these in your collection. This can also be done using batch renaming using programs like Adobe Bridge, IrfanView (free), or Inselect (free). Inselect can also parse out multiple slides in one image, read QR codes, and rename files based on the embedded information. Best practice avoids spaces in image file names. Note that using examples like: "country code"+"state code"+"verbatim directions"+"collector name"+"date"+"serial identifier" can work, but note that if any of those data change, then the file name will not help to understand what is in the image or help to find images.
